In [18]:
import numpy as np
import pandas as pd
np.random.seed(123)
n_sample = 1000
classification_0_ratio = 0.9
n_classification_0 = int(n_sample * classification_0_ratio)
n_classification_1 = n_sample - n_classification_0

In [19]:
n_classification_0, n_classification_1

(900, 100)

In [20]:
# Creating a dataframe with imbalanced dataset
classification_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'target'   : [0] * n_classification_0
    
})
classification_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'feature2' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'target'   : [1] * n_classification_1
})

In [21]:
df=pd.concat([classification_0, classification_1]).reset_index(drop=True)

In [22]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [23]:
df.tail()

     feature1  feature2  target
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

In [24]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [25]:
## upsampling the minority class
df_minority = df[df['target'] ==1]
df_majority = df[df['target'] ==0]