In [111]:
import numpy as np
import pandas as pd
np.random.seed(123)
n_sample = 1000
classification_0_ratio = 0.9
n_classification_0 = int(n_sample * classification_0_ratio)
n_classification_1 = n_sample - n_classification_0

In [112]:
n_classification_0, n_classification_1

(900, 100)

In [113]:
# Creating a dataframe with imbalanced dataset
classification_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'target'   : [0] * n_classification_0
    
})
classification_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'feature2' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'target'   : [1] * n_classification_1
})

In [114]:
df=pd.concat([classification_0, classification_1]).reset_index(drop=True)

In [115]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [116]:
df.tail()

     feature1  feature2  target
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

In [117]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [118]:
## upsampling the minority class
df_minority = df[df['target'] ==1]
df_majority = df[df['target'] ==0]

In [119]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,n_samples=len(df_majority),random_state=243)

In [120]:
df_minority_upsampled.shape

(900, 3)

In [121]:
df_minority_upsampled.head()

     feature1  feature2  target
925  2.193094  2.196780       1
990  3.063905  0.919587       1
941  1.140312  1.976772       1
969  2.917884  3.508705       1
952  1.188902  2.189189       1

In [122]:
df_upsampled=pd.concat([df_majority, df_minority_upsampled])

In [123]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down sampling

In [124]:
np.random.seed(123)
n_sample = 1000
classification_0_ratio = 0.9
n_classification_0 = int(n_sample * classification_0_ratio)
n_classification_1 = n_sample - n_classification_0

classification_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_classification_0),
    'target'   : [0] * n_classification_0
    
})
classification_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'feature2' : np.random.normal(loc=2, scale=1, size=n_classification_1),
    'target'   : [1] * n_classification_1
})

df=pd.concat([classification_0, classification_1]).reset_index(drop=True)

In [125]:
# Separate majority and minority classes
df_majority = df[df.target == 0]
df_minority = df[df.target == 1]

In [126]:
df_majority_downsampled = df_majority.sample(
    n=len(df_minority),       # same number as minority
    random_state=123
)

In [127]:
df_majority_downsampled.shape

(100, 3)

In [128]:
df_majority_downsampled.head()

     feature1  feature2  target
613 -1.147525  0.284447       0
524 -0.448392  0.777222       0
690 -1.576233  0.187258       0
457  1.601908 -1.080462       0
85  -1.085902 -1.775243       0

In [129]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority])

In [130]:
print(df_downsampled['target'].value_counts())

target
0    100
1    100
Name: count, dtype: int64